/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Hodl } from "./Hodl";
export * as factories from "./factories";
export { Hodl__factory } from "./factories/Hodl__factory";
